### ISSUE TITLE
Is it possible to use a custom browser like chrome to run the test in different threads?

### ISSUE THREAD

**Issue by riccardogiorato** [trentrand/cypress-utils#19]
Is it possible to use a custom browser like chrome to run the test in different threads?

I tried passing --browser=chrome to cypress-utils command but it's printing an error saying that browser option is not supported. Is there a workaround?

**Comment by trentrand** [comment]
I believe we'd just need to update cypress-utils to pass-through the parameter.

Someone added support to do this for the Cypress CLI `--reporter` option, see here:
https://github.com/trentrand/cypress-utils/blob/master/index.js#L82-L88

I think a more holistic approach would be to pass-through any unrecognized CLI options to the Cypress CLI.

**Comment by trentrand** [comment]
Thanks for reporting this issue!

I've published a fix in version 2.3.0.
See the release here for more details: https://github.com/trentrand/cypress-utils/releases/tag/v2.3.0
